name: visiting_card_app
description: This card has my professional details

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - images/IMG_20191024_154818.jpg

  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf
    - family: ABeeZee
      fonts:
        - asset: fonts/ABeeZee/ABeeZee-Regular.ttf
    - family: Asap_Condensed
      fonts:
        - asset: fonts/Asap_Condensed/AsapCondensed-Medium.ttf